### ISSUE TITLE
Removal of Task Button Unresponsive When Clicked Inside the 'Into' Mark

### ISSUE THREAD

**Issue by jelanmathewjames** [2002SUJITH/To-Do-List-App#1]
The task cannot be removed when it's clicked on the exact position of the 'into' mark depicted inside the <i> element. It appears that the remove button is unresponsive in this specific scenario.

One possible solution is to add the 'removeIcon' class to the <i> element and, when clicked, remove the parent element by referencing the class name.

**Comment by 07SUJITH** [comment]
fixed unresponsive nature of button.
